In [136]:
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [137]:
df_trips = pd.read_csv("data/trips.txt")
df_routes = pd.read_csv("data/routes.txt")
df_stops = pd.read_csv("data/stops.txt")
df_stop_times = pd.read_csv("data/stop_times.txt")
df_pathways = pd.read_csv("data/pathways.txt")

# Egy megállóból elérhető szomszédok keresése

## Járatok

In [138]:
df_trips.head(5)

,route_id,trip_id,service_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,8140,C0418310,C04183AHPMAA-011,"Soroksár, Molnár-sziget",0,C04183_8140_1_5,Y701,1.0,1.0
1,8140,C0418311,C04183AHPMAA-011,Csepel-Királyerdő,1,C04183_8140_1_6,Y702,1.0,1.0
2,8140,C0418312,C04183AHPMAA-011,"Soroksár, Molnár-sziget",0,C04183_8140_1_7,Y701,1.0,1.0
3,8140,C0418313,C04183AHPMAA-011,Csepel-Királyerdő,1,C04183_8140_1_8,Y702,1.0,1.0
4,8140,C0418314,C04183AHPMAA-011,"Soroksár, Molnár-sziget",0,C04183_8140_1_9,Y701,1.0,1.0

## Melyik járat, melyik megállóban mikor áll meg?

In [139]:
df_stop_times.head(5)

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,C0418310,F04181,08:03:00,08:03:00,0,NaN,NaN,NaN,0.0
1,C0418310,F04526,08:06:00,08:06:00,1,NaN,NaN,NaN,160.0
2,C0418311,F04526,08:30:00,08:30:00,0,NaN,NaN,NaN,0.0
3,C0418311,F04181,08:33:00,08:33:00,1,NaN,NaN,NaN,160.0
4,C0418312,F04181,08:33:00,08:33:00,0,NaN,NaN,NaN,0.0

## Most a string arrival_time-ből csináljunk számokat
Mert igy jóval gyorsabb lesz a lekérdezés

In [140]:
def arrival_time_to_min(astr):
    [h,m,s]=astr.split(':')
    return int(h)*60+int(m)

In [141]:
df_stop_times["arrival_time_min"]=df_stop_times["arrival_time"].apply(arrival_time_to_min)
df_stop_times[["trip_id","stop_id","arrival_time","stop_sequence","arrival_time_min"]].head(5)

    trip_id stop_id arrival_time  stop_sequence  arrival_time_min
0  C0418310  F04181     08:03:00              0               483
1  C0418310  F04526     08:06:00              1               486
2  C0418311  F04526     08:30:00              0               510
3  C0418311  F04181     08:33:00              1               513
4  C0418312  F04181     08:33:00              0               513

## Adott megállóban melyik járatok állnak meg X időpont után

"008152", # Mester utca / könyveskalman
"008163" # Újpest Városkapu
"F00191", # Margit híd, budai hídfő H
"F01083" # Király utca / Erzsébet körút
"F01755", # Örs vezér tere M+H'
"F01083" #  Oktogon M
"F02268", # KFKI
"009019" # Gödöllő

In [142]:
stop_id = "F00191"
arrival_time_min=arrival_time_to_min("9:01:00")
arrival_time_min

541

In [143]:
a=df_stops.query(f'stop_id == "{stop_id}"')["stop_name"]
stop_name=a.values[0]
stop_name

'Margit híd, budai hídfő H'

In [144]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > {arrival_time_min}'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name
df_megallo_jaratok[["stop_id","stop_name","trip_id", "route_id","arrival_time", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,arrival_time,stop_headsign,stop_sequence
36,F00191,"Margit híd, budai hídfő H",D0427910466,1910,09:02:00,NaN,2
1102,F00191,"Margit híd, budai hídfő H",D063983577,2910,09:05:00,"Zugliget, Libegő",2
271,F00191,"Margit híd, budai hídfő H",D044333587,0910,09:15:00,Rózsadomb ► Széll Kálmán tér M,2
416,F00191,"Margit híd, budai hídfő H",D05242569,VP06,23:33:00,NaN,11

In [145]:
df_megallo_jaratok2 = pd.merge( df_megallo_jaratok, df_routes, left_on="route_id", right_on="route_id")
df_megallo_jaratok2[["stop_id","stop_name","trip_id", "route_id","route_short_name", "arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,route_short_name,arrival_time,arrival_time_min,stop_headsign,stop_sequence
0,F00191,"Margit híd, budai hídfő H",D0427910466,1910,191,09:02:00,542,NaN,2
1,F00191,"Margit híd, budai hídfő H",D063983577,2910,291,09:05:00,545,"Zugliget, Libegő",2
2,F00191,"Margit híd, budai hídfő H",D044333587,0910,91,09:15:00,555,Rózsadomb ► Széll Kálmán tér M,2
3,F00191,"Margit híd, budai hídfő H",D05242569,VP06,6,23:33:00,1413,NaN,11

## Kezdjük el keresi a megálló szomszédait

### stop_times mintha erre lenne kitalálva, mert valójában egy trip későbbi megállóit keresem!

In [146]:
trip_id="D063983577"
arrival_time_min = 542

In [147]:
df_stop_times.query(f'trip_id == "{trip_id}" and arrival_time_min > {arrival_time_min}')

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min
5512833,D063983577,F00191,09:05:00,09:05:00,2,"Zugliget, Libegő",NaN,NaN,1640.0,545
5512834,D063983577,F00233,09:07:00,09:07:00,3,"Zugliget, Libegő",NaN,NaN,2131.0,547
5512835,D063983577,F00230,09:08:00,09:08:00,4,"Zugliget, Libegő",NaN,NaN,2414.0,548
5512836,D063983577,F00228,09:09:00,09:09:00,5,"Zugliget, Libegő",NaN,NaN,2756.0,549
5512837,D063983577,F00223,09:10:00,09:10:00,6,"Zugliget, Libegő",NaN,NaN,3130.0,550
5512838,D063983577,F00221,09:11:00,09:11:00,7,"Zugliget, Libegő",NaN,NaN,3497.0,551
5512839,D063983577,F00219,09:13:00,09:13:00,8,"Zugliget, Libegő",NaN,NaN,3942.0,553
5512840,D063983577,F00217,09:14:00,09:14:00,9,"Zugliget, Libegő",NaN,NaN,4190.0,554
5512841,D063983577,F00213,09:15:00,09:15:00,10,"Zugliget, Libegő",NaN,NaN,4427.0,555
5512842,D063983577,009512,09:16:00,09:16:00,11,"Zugliget, Libegő",NaN,NaN,4917.0,556
5512843,D063983577,009513,09:17:00,09:17:00,12,"Zugliget, Libegő",NaN,NaN,5235.0,557
5512844,D063983577,009508,09:18:00,09:18:00,13,"Zugliget, Libegő",NaN,NaN,5410.0,558
5512845,D063983577,009511,09:19:00,09:19:00,14,"Zugliget, Libegő",NaN,NaN,5760.0,559
5512846,D063983577,009540,09:20:00,09:20:00,15,"Zugliget, Libegő",NaN,NaN,5959.0,560
5512847,D063983577,F00164,09:21:00,09:21:00,16,"Zugliget, Libegő",NaN,NaN,6252.0,561
5512848,D063983577,F00168,09:22:00,09:22:00,17,"Zugliget, Libegő",NaN,NaN,6644.0,562
5512849,D063983577,F02352,09:23:00,09:23:00,18,"Zugliget, Libegő",NaN,NaN,7073.0,563
5512850,D063983577,F02385,09:24:00,09:24:00,19,"Zugliget, Libegő",NaN,NaN,7581.0,564
5512851,D063983577,F02384,09:25:00,09:25:00,20,"Zugliget, Libegő",NaN,NaN,7948.0,565
5512852,D063983577,F02382,09:26:00,09:26:00,21,"Zugliget, Libegő",1.0,NaN,8232.0,566

# Járattal elérhető szomszédok meghatározása

Először valamilyen ciklusra gondoltam, de az inner join sokkal jobb

Előről kezdem és megpróbálom a részfolyamatokat összeilleszteni

In [148]:
stop_id = "F01034"
arrival_time_min=arrival_time_to_min("9:01:00")
arrival_time_min

541

In [149]:
a=df_stops.query(f'stop_id == "{stop_id}"')["stop_name"]
stop_name=a.values[0]
stop_name

'Király utca / Erzsébet körút'

Melyik járatok állnak meg itt X időpont után:

In [150]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > {arrival_time_min}'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name
df_megallo_jaratok[["stop_id","stop_name","trip_id", "route_id","arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
1508,F01034,Király utca / Erzsébet körút,D0592567,4780,09:02:00,542,Kossuth Lajos tér M,6
1619,F01034,Király utca / Erzsébet körút,D059411951,4700,09:02:00,542,Kossuth Lajos tér M,9

Kozmetika, hogy legyen járatszám amit értek is

In [151]:
df_megallo_jaratok2 = pd.merge( df_megallo_jaratok, df_routes, left_on="route_id", right_on="route_id")
df_megallo_jaratok2[["stop_id","stop_name","trip_id", "route_id","route_short_name", "arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,trip_id,route_id,route_short_name,arrival_time,arrival_time_min,stop_headsign,stop_sequence
0,F01034,Király utca / Erzsébet körút,D0592567,4780,78,09:02:00,542,Kossuth Lajos tér M,6
1,F01034,Király utca / Erzsébet körút,D059411951,4700,70,09:02:00,542,Kossuth Lajos tér M,9

### Szomszédokat egy left join-nal fogok keresni

In [152]:
df_szomszedok = pd.merge( df_megallo_jaratok2, df_stop_times, how="left", left_on="trip_id", right_on="trip_id")
df_szomszedok.columns

Index(['trip_id', 'stop_id_x', 'arrival_time_x', 'departure_time_x',
       'stop_sequence_x', 'stop_headsign_x', 'pickup_type_x',
       'drop_off_type_x', 'shape_dist_traveled_x', 'arrival_time_min_x',
       'route_id', 'service_id', 'trip_headsign', 'direction_id', 'block_id',
       'shape_id', 'wheelchair_accessible', 'bikes_allowed', 'stop_name',
       'agency_id', 'route_short_name', 'route_long_name', 'route_type',
       'route_desc', 'route_color', 'route_text_color', 'route_sort_order',
       'stop_id_y', 'arrival_time_y', 'departure_time_y', 'stop_sequence_y',
       'stop_headsign_y', 'pickup_type_y', 'drop_off_type_y',
       'shape_dist_traveled_y', 'arrival_time_min_y'],
      dtype='object')

Túl korai járatokat törlöm

In [153]:
indices_to_drop = df_szomszedok [ df_szomszedok["arrival_time_min_y"] < arrival_time_min ].index
df_szomszedok.drop( indices_to_drop, inplace= True)

In [154]:
df_szomszedok[["trip_id","stop_id_x","arrival_time_x","stop_name","stop_id_y","arrival_time_y"]]

,trip_id,stop_id_x,arrival_time_x,stop_name,stop_id_y,arrival_time_y
6,D0592567,F01034,09:02:00,Király utca / Erzsébet körút,F01034,09:02:00
7,D0592567,F01034,09:02:00,Király utca / Erzsébet körút,F01033,09:03:00
8,D0592567,F01034,09:02:00,Király utca / Erzsébet körút,F01075,09:04:00
9,D0592567,F01034,09:02:00,Király utca / Erzsébet körút,009025,09:06:00
10,D0592567,F01034,09:02:00,Király utca / Erzsébet körút,F00938,09:08:00
11,D0592567,F01034,09:02:00,Király utca / Erzsébet körút,F00970,09:10:00
20,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,F01041,09:01:00
21,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,F01034,09:02:00
22,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,F01033,09:03:00
23,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,F01075,09:04:00
24,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,009025,09:06:00
25,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,F00938,09:08:00
26,D059411951,F01034,09:02:00,Király utca / Erzsébet körút,F00970,09:10:00

In [181]:
df_szomszedok2 = pd.merge(df_szomszedok, df_stops, how = "left", left_on="stop_id_y", right_on="stop_id")
df_szomszedok2.columns
df_szomszedok2[["trip_id","route_short_name", "stop_id_x","arrival_time_x","stop_name_x","stop_id_y","stop_id", "stop_name_y", "arrival_time_y"]]

,trip_id,route_short_name,stop_id_x,arrival_time_x,stop_name_x,stop_id_y,stop_id,stop_name_y,arrival_time_y
0,D0592567,78,F01034,09:02:00,Király utca / Erzsébet körút,F01034,F01034,Király utca / Erzsébet körút,09:02:00
1,D0592567,78,F01034,09:02:00,Király utca / Erzsébet körút,F01033,F01033,Akácfa utca,09:03:00
2,D0592567,78,F01034,09:02:00,Király utca / Erzsébet körút,F01075,F01075,Opera M,09:04:00
3,D0592567,78,F01034,09:02:00,Király utca / Erzsébet körút,009025,009025,Zichy Jenő utca,09:06:00
4,D0592567,78,F01034,09:02:00,Király utca / Erzsébet körút,F00938,F00938,Báthory utca / Bajcsy-Zsilinszky út,09:08:00
5,D0592567,78,F01034,09:02:00,Király utca / Erzsébet körút,F00970,F00970,Kossuth Lajos tér M,09:10:00
6,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,F01041,F01041,Izabella utca / Király utca,09:01:00
7,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,F01034,F01034,Király utca / Erzsébet körút,09:02:00
8,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,F01033,F01033,Akácfa utca,09:03:00
9,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,F01075,F01075,Opera M,09:04:00
10,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,009025,009025,Zichy Jenő utca,09:06:00
11,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,F00938,F00938,Báthory utca / Bajcsy-Zsilinszky út,09:08:00
12,D059411951,70,F01034,09:02:00,Király utca / Erzsébet körút,F00970,F00970,Kossuth Lajos tér M,09:10:00

In [182]:
df_szomszedok2[["stop_id", "trip_id", "route_short_name", "stop_name_y", "arrival_time_y"]].values

array([['F01034', 'D0592567', '78', 'Király utca / Erzsébet körút',
        '09:02:00'],
       ['F01033', 'D0592567', '78', 'Akácfa utca', '09:03:00'],
       ['F01075', 'D0592567', '78', 'Opera M', '09:04:00'],
       ['009025', 'D0592567', '78', 'Zichy Jenő utca', '09:06:00'],
       ['F00938', 'D0592567', '78',
        'Báthory utca / Bajcsy-Zsilinszky út', '09:08:00'],
       ['F00970', 'D0592567', '78', 'Kossuth Lajos tér M', '09:10:00'],
       ['F01041', 'D059411951', '70', 'Izabella utca / Király utca',
        '09:01:00'],
       ['F01034', 'D059411951', '70', 'Király utca / Erzsébet körút',
        '09:02:00'],
       ['F01033', 'D059411951', '70', 'Akácfa utca', '09:03:00'],
       ['F01075', 'D059411951', '70', 'Opera M', '09:04:00'],
       ['009025', 'D059411951', '70', 'Zichy Jenő utca', '09:06:00'],
       ['F00938', 'D059411951', '70',
        'Báthory utca / Bajcsy-Zsilinszky út', '09:08:00'],
       ['F00970', 'D059411951', '70', 'Kossuth Lajos tér M', '09:10:00']],
      dtype=object)

## Keressük meg egy útvonalon a megállók neveit

Megoldási terv: Keresek egy routet-t és az első trip-et benne.

Ahhoz a triphez lekérdezzük a megállókat.
Utána majd mellétesszük a neveket is

In [157]:
df_trips.groupby(["route_id"]).agg({"route_id":"first","trip_id":"first", "trip_headsign":"first"})

         route_id     trip_id              trip_headsign
route_id
0050         0050    D0166810               Pasaréti tér
0070         0070   D06142101    Újpalota, Nyírpalota út
0075         0075    D0172110          Blaha Lujza tér M
0078         0078     C755691    Újpalota, Nyírpalota út
0085         0085    D0166110   Kelenföld vasútállomás M
...           ...         ...                        ...
VP41         VP41  D056341087      Kamaraerdei Ifj. Park
VP50         VP50     D064891  Pestszentlőrinc, Béke tér
VP52         VP52     D048871  P.erzsébet, Pacsirtatelep
VP60         VP60     C937781             Széchenyi-hegy
VP601       VP601     D063421                Pethényi út

[376 rows x 3 columns]

### Melyik megállókban áll meg a 4-6-os ?

#### Mikor indul reggel a 4-6-os

A 3060-as járat első indulását keresem.
A groupby és agg funckiók miatt fontos

In [158]:
df_trips[ df_trips["route_id"].isin(["3060"]) ].groupby(["route_id"]).agg({"route_id":"first","trip_id":"first", "trip_headsign":"first"})["trip_id"]

route_id
3060    D015151403
Name: trip_id, dtype: object

Megvan a trip_id

In [159]:
df_stop_times[ df_stop_times["trip_id"] == "D015151066"]

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min
1428865,D015151066,F01998,05:47:00,05:47:00,0,Széll Kálmán tér M,NaN,NaN,0.0,347
1428866,D015151066,F01992,05:49:00,05:49:00,1,Széll Kálmán tér M,NaN,NaN,544.0,349
1428867,D015151066,F02225,05:50:00,05:50:00,2,Széll Kálmán tér M,NaN,NaN,1087.0,350
1428868,D015151066,F01374,05:51:00,05:51:00,3,Széll Kálmán tér M,NaN,NaN,1750.0,351
1428869,D015151066,F01380,05:53:00,05:53:00,4,Széll Kálmán tér M,NaN,NaN,2073.0,353
1428870,D015151066,F01191,05:55:00,05:55:00,5,Széll Kálmán tér M,NaN,NaN,2395.0,355
1428871,D015151066,F01199,05:57:00,05:57:00,6,Széll Kálmán tér M,NaN,NaN,2948.0,357
1428872,D015151066,F01200,05:58:00,05:58:00,7,Széll Kálmán tér M,NaN,NaN,3233.0,358
1428873,D015151066,F01168,06:00:00,06:00:00,8,Széll Kálmán tér M,NaN,NaN,3677.0,360
1428874,D015151066,F01111,06:01:00,06:01:00,9,Széll Kálmán tér M,NaN,NaN,4109.0,361
1428875,D015151066,F01035,06:02:00,06:02:00,10,Széll Kálmán tér M,NaN,NaN,4511.0,362
1428876,D015151066,F01082,06:04:00,06:04:00,11,Széll Kálmán tér M,NaN,NaN,4914.0,364
1428877,D015151066,F00933,06:06:00,06:06:00,12,Széll Kálmán tér M,NaN,NaN,5596.0,366
1428878,D015151066,F00925,06:08:00,06:08:00,13,Széll Kálmán tér M,NaN,NaN,6287.0,368
1428879,D015151066,F00141,06:10:00,06:10:00,14,Széll Kálmán tér M,NaN,NaN,6764.0,370
1428880,D015151066,F00192,06:11:00,06:11:00,15,Széll Kálmán tér M,NaN,NaN,7096.0,371
1428881,D015151066,F00198,06:13:00,06:13:00,16,Széll Kálmán tér M,NaN,NaN,7841.0,373
1428882,D015151066,F00307,06:15:00,06:15:00,17,Széll Kálmán tér M,NaN,NaN,8311.0,375
1428883,D015151066,F02476,06:17:00,06:17:00,18,Széll Kálmán tér M,1.0,NaN,8529.0,377

### Most tegyük mellé a neveket is!

A hátsó stop_name oszlopban látszik

In [160]:
pd.merge( df_stop_times[ df_stop_times["trip_id"] == "D015151066"], df_stops, on="stop_id")

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding
0,D015151066,F01998,05:47:00,05:47:00,0,Széll Kálmán tér M,NaN,NaN,0.0,347,Újbuda-központ M,47.474042,19.046862,F01998,NaN,NaN,NaN,1.0
1,D015151066,F01992,05:49:00,05:49:00,1,Széll Kálmán tér M,NaN,NaN,544.0,349,Budafoki út / Szerémi sor,47.474114,19.053747,F01992,NaN,NaN,NaN,1.0
2,D015151066,F02225,05:50:00,05:50:00,2,Széll Kálmán tér M,NaN,NaN,1087.0,350,"Petőfi híd, budai hídfő",47.476956,19.059572,F02225,NaN,NaN,NaN,1.0
3,D015151066,F01374,05:51:00,05:51:00,3,Széll Kálmán tér M,NaN,NaN,1750.0,351,Boráros tér H,47.480400,19.066697,F01374,NaN,NaN,NaN,2.0
4,D015151066,F01380,05:53:00,05:53:00,4,Széll Kálmán tér M,NaN,NaN,2073.0,353,Mester utca / Ferenc körút,47.482775,19.068848,F01380,NaN,NaN,NaN,1.0
5,D015151066,F01191,05:55:00,05:55:00,5,Széll Kálmán tér M,NaN,NaN,2395.0,355,Corvin-negyed M,47.485500,19.069924,F01191,NaN,NaN,NaN,1.0
6,D015151066,F01199,05:57:00,05:57:00,6,Széll Kálmán tér M,NaN,NaN,2948.0,357,Harminckettesek tere,47.490357,19.070841,F01199,NaN,NaN,NaN,1.0
7,D015151066,F01200,05:58:00,05:58:00,7,Széll Kálmán tér M,NaN,NaN,3233.0,358,Rákóczi tér M,47.492866,19.071187,F01200,NaN,NaN,NaN,1.0
8,D015151066,F01168,06:00:00,06:00:00,8,Széll Kálmán tér M,NaN,NaN,3677.0,360,Blaha Lujza tér M,47.496770,19.070725,F01168,NaN,NaN,NaN,1.0
9,D015151066,F01111,06:01:00,06:01:00,9,Széll Kálmán tér M,NaN,NaN,4109.0,361,Wesselényi utca / Erzsébet körút,47.500350,19.068934,F01111,NaN,NaN,NaN,1.0
10,D015151066,F01035,06:02:00,06:02:00,10,Széll Kálmán tér M,NaN,NaN,4511.0,362,Király utca / Erzsébet körút,47.503256,19.065856,F01035,NaN,NaN,NaN,1.0
11,D015151066,F01082,06:04:00,06:04:00,11,Széll Kálmán tér M,NaN,NaN,4914.0,364,Oktogon M,47.505964,19.062405,F01082,NaN,NaN,NaN,1.0
12,D015151066,F00933,06:06:00,06:06:00,12,Széll Kálmán tér M,NaN,NaN,5596.0,366,Nyugati pályaudvar M,47.510300,19.056167,F00933,NaN,NaN,NaN,1.0
13,D015151066,F00925,06:08:00,06:08:00,13,Széll Kálmán tér M,NaN,NaN,6287.0,368,Jászai Mari tér,47.513116,19.048175,F00925,NaN,NaN,NaN,1.0
14,D015151066,F00141,06:10:00,06:10:00,14,Széll Kálmán tér M,NaN,NaN,6764.0,370,Margitsziget / Margit híd,47.514717,19.042479,F00141,NaN,NaN,NaN,1.0
15,D015151066,F00192,06:11:00,06:11:00,15,Széll Kálmán tér M,NaN,NaN,7096.0,371,"Margit híd, budai hídfő H",47.514653,19.038164,F00192,NaN,NaN,NaN,1.0
16,D015151066,F00198,06:13:00,06:13:00,16,Széll Kálmán tér M,NaN,NaN,7841.0,373,Mechwart liget,47.510767,19.031447,F00198,NaN,NaN,NaN,1.0
17,D015151066,F00307,06:15:00,06:15:00,17,Széll Kálmán tér M,NaN,NaN,8311.0,375,Széna tér,47.508140,19.026735,F00307,NaN,NaN,NaN,1.0
18,D015151066,F02476,06:17:00,06:17:00,18,Széll Kálmán tér M,1.0,NaN,8529.0,377,Széll Kálmán tér M,47.507384,19.024492,F02476,NaN,NaN,NaN,1.0

# Kódrészlet ami egy vonal megállóit keresi meg
Most egy kis kódrészlet keresi nekem az adott vonal megállóit.
Ezt lehet majd beletenni egy függvénybe

In [161]:
#route_id = "3060"
#route_id="3040"
route_id="0090"
elso_trip = df_trips[ df_trips["route_id"] == route_id ].groupby(["route_id"]).agg({"route_id":"first","trip_id":"first", "trip_headsign":"first"})["trip_id"].iloc[0]
a=pd.merge( df_stop_times[ df_stop_times["trip_id"] == elso_trip], df_stops, on="stop_id")
a["route_id"]=route_id
a[["route_id","trip_id","stop_id","stop_name","arrival_time","departure_time","stop_lat","stop_lon"]]

,route_id,trip_id,stop_id,stop_name,arrival_time,departure_time,stop_lat,stop_lon
0,0090,D033981412,F01636,Kőbánya alsó vasútállomás,04:36:00,04:36:00,47.483652,19.127839
1,0090,D033981412,F01653,Szent László tér,04:37:00,04:37:00,47.485925,19.131093
2,0090,D033981412,F01641,Liget tér,04:39:00,04:39:00,47.482795,19.130358
3,0090,D033981412,F01571,Kőbánya alsó vasútállomás (Mázsa tér),04:40:00,04:40:00,47.482879,19.125715
4,0090,D033981412,F01563,Egészségház,04:42:00,04:42:00,47.484126,19.116668
5,0090,D033981412,F01733,Eiffel Műhelyház,04:43:00,04:43:00,47.485136,19.112914
6,0090,D033981412,F01267,Kőbányai út / Könyves Kálmán körút,04:45:00,04:45:00,47.486740,19.106971
7,0090,D033981412,008036,Kőbányai út 31.,04:45:00,04:45:00,47.487461,19.104252
8,0090,D033981412,F01187,Orczy tér,04:47:00,04:48:00,47.489470,19.090495
9,0090,D033981412,F01223,Kálvária tér,04:49:00,04:49:00,47.488890,19.085146
10,0090,D033981412,F01176,Muzsikus cigányok parkja,04:50:00,04:50:00,47.489278,19.079639
11,0090,D033981412,F01207,Horváth Mihály tér,04:51:00,04:51:00,47.489594,19.076707
12,0090,D033981412,F01204,Harminckettesek tere,04:53:00,04:53:00,47.489514,19.071306
13,0090,D033981412,F01175,Szentkirályi utca,04:54:00,04:54:00,47.489191,19.066807
14,0090,D033981412,F01010,Kálvin tér M,04:56:00,04:56:00,47.490010,19.061978
15,0090,D033981412,F01013,Astoria M,04:58:00,04:58:00,47.494145,19.060146
16,0090,D033981412,009309,Deák Ferenc tér M,05:00:00,05:00:00,47.497449,19.055715
17,0090,D033981412,048506,Szent István Bazilika,05:01:00,05:01:00,47.500273,19.055025
18,0090,D033981412,F00942,Arany János utca M,05:02:00,05:02:00,47.503304,19.055105
19,0090,D033981412,F00940,Báthory utca / Bajcsy-Zsilinszky út,05:03:00,05:03:00,47.507189,19.055730
20,0090,D033981412,F01029,Nyugati pályaudvar M,05:05:00,05:06:00,47.509806,19.057151
21,0090,D033981412,F00929,Jászai Mari tér,05:08:00,05:08:00,47.512558,19.050126
22,0090,D033981412,F00237,"Margit híd, budai hídfő H",05:10:00,05:10:00,47.515518,19.038339
23,0090,D033981412,F00247,Császár-Komjádi uszoda,05:12:00,05:12:00,47.521409,19.038272
24,0090,D033981412,F00245,Zsigmond tér,05:13:00,05:13:00,47.524991,19.037951
25,0090,D033981412,F00137,Kolosy tér,05:15:00,05:15:00,47.528586,19.039001
26,0090,D033981412,F00603,Nagyszombat utca,05:16:00,05:16:00,47.531833,19.040023
27,0090,D033981412,F00604,Tímár utca,05:17:00,05:17:00,47.535152,19.039969
28,0090,D033981412,F00606,Kiscelli utca,05:18:00,05:18:00,47.538723,19.040500
29,0090,D033981412,F00611,Flórián tér,05:20:00,05:20:00,47.542896,19.042252
30,0090,D033981412,F00580,Raktár utca,05:21:00,05:21:00,47.545288,19.042837
31,0090,D033981412,F00573,"Óbuda, Bogdáni út",05:23:00,05:23:00,47.550712,19.041826

## Melyik járatok állnak meg ebben a megállóban ?

In [162]:
df_stop_times[ df_stop_times["stop_id"] == "048506"]

,trip_id,stop_id,arrival_time,departure_time,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,arrival_time_min
548787,C96610106,048506,07:27:00,07:27:00,9,Zugló vasútállomás,NaN,NaN,3713.0,447
548839,C96610111,048506,07:37:00,07:37:00,9,Zugló vasútállomás,NaN,NaN,3713.0,457
548889,C96610116,048506,07:44:00,07:44:00,9,Zugló vasútállomás,NaN,NaN,3713.0,464
548941,C96610121,048506,07:52:00,07:52:00,9,Zugló vasútállomás,NaN,NaN,3713.0,472
548966,C966101221,048506,16:35:00,16:35:00,9,Zugló vasútállomás,NaN,NaN,3713.0,995
...,...,...,...,...,...,...,...,...,...,...
5688598,D066221107,048506,03:09:00,03:09:00,42,"Rákospalota, Székely Elek út",NaN,NaN,20957.0,189
5688676,D066221115,048506,03:30:00,03:30:00,42,"Rákospalota, Kossuth utca",NaN,NaN,20957.0,210
5688727,D066221125,048506,03:50:00,03:50:00,26,NaN,NaN,NaN,13366.0,230
5688784,D066221131,048506,04:09:00,04:09:00,42,Újpest-központ M,NaN,NaN,20957.0,249
5688841,D066221139,048506,04:29:00,04:29:00,42,Újpest-központ M,NaN,NaN,20957.0,269

Látszik, hogy jó sok indulás van ebből a megállóból

## Adatvizsgálat: hogyan lesznek meg a fő megállók?

In [163]:
stop_id = "048506" # Szent István Bazilika
#stop_id = "F01029" # Nyugati
parent_stop_id = df_stops[ df_stops["stop_id"] == stop_id]["parent_station"].iloc[0]
parent_stop_id

nan

In [164]:
if parent_stop_id is not np.nan:
        stop_id = parent_stop_id
stop_name = df_stops[ df_stops["stop_id"] == stop_id]["stop_name"].iloc[0]
stop_name

'Szent István Bazilika'

Itt látszik, hogy ez igy nem lesz OK. Az adatok nem tartalmaznak információt arra, hogy melyik az al, vagy melyik a fő megálló

## Melyik útvonalak állnak meg ebben a megállóban?

In [165]:
df_megallo_jaratok = pd.merge( df_stop_times[ df_stop_times["stop_id"] == stop_id], df_trips, left_on="trip_id", right_on="trip_id").drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,stop_headsign,stop_sequence
0,048506,Szent István Bazilika,4720,Zugló vasútállomás,9
544,048506,Szent István Bazilika,9140,"Káposztásmegyer, Mogyoródi-patak",30
558,048506,Szent István Bazilika,9310,Nyugati pályaudvar M ► Zöldmál,2
581,048506,Szent István Bazilika,9141,Újpest-központ M,12
607,048506,Szent István Bazilika,9500,"Rákospalota, Székely Elek út",42
608,048506,Szent István Bazilika,9501,NaN,42
635,048506,Szent István Bazilika,0090,"Óbuda, Bogdáni út",17

## Sajnos nem világos miért nem lehet két mezőt könnyen selectezni logikai operátorokkal

In [166]:
#df_megallo_jaratok = pd.merge( df_stop_times[ df_stop_times["stop_id"] == stop_id and df_stop_times["arrival_time_min"] > 60*8+15 ] , df_trips, left_on="trip_id", right_on="trip_id").drop_duplicates("route_id")
#df_megallo_jaratok["stop_id"]=stop_id
#df_megallo_jaratok["stop_name"]=stop_name

#df_megallo_jaratok[["stop_id","stop_name","route_id","stop_headsign","stop_sequence"]]

In [167]:
 a = pd.Series(df_stop_times["stop_id"] == stop_id)
 a

0          False
1          False
2          False
3          False
4          False
           ...
5752577    False
5752578    False
5752579    False
5752580    False
5752581    False
Name: stop_id, Length: 5752582, dtype: bool

In [168]:
 b = pd.Series(df_stop_times["arrival_time_min"] > 60*8+15 )
 b

0          False
1          False
2           True
3           True
4           True
           ...
5752577     True
5752578     True
5752579     True
5752580     True
5752581     True
Name: arrival_time_min, Length: 5752582, dtype: bool

In [169]:
a & b

0          False
1          False
2          False
3          False
4          False
           ...
5752577    False
5752578    False
5752579    False
5752580    False
5752581    False
Length: 5752582, dtype: bool

## Melyik járatok állnak meg ebben a megállóban reggel 9:00 körül (1)

In [170]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time.str.startswith("09").values'), df_trips, left_on='trip_id', right_on='trip_id').sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","arrival_time", "arrival_time_min","stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
54,048506,Szent István Bazilika,0090,09:00:00,540,"Óbuda, Bogdáni út",17
18,048506,Szent István Bazilika,4720,09:00:00,540,Zugló vasútállomás,9

## Melyik járatok állnak meg ebben a megállóban reggel 10:00 körül (2)

In [171]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time > "10:00:00"'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
3,048506,Szent István Bazilika,4720,10:01:00,601,Zugló vasútállomás,9
1093,048506,Szent István Bazilika,0090,10:06:00,606,"Óbuda, Bogdáni út",17
401,048506,Szent István Bazilika,9500,24:09:00,1449,"Rákospalota, Székely Elek út",12
486,048506,Szent István Bazilika,9140,24:19:00,1459,"Káposztásmegyer, Mogyoródi-patak",30

## Most inkább nem string-et keresünk, hanem számot
Kétszer olyan gyors lett a futtatás

In [172]:
df_megallo_jaratok = pd.merge( df_stop_times.query(f'stop_id == "{stop_id}" and arrival_time_min > 60*10'), df_trips, left_on="trip_id", right_on="trip_id").sort_values(["arrival_time"]).drop_duplicates("route_id")
df_megallo_jaratok["stop_id"]=stop_id
df_megallo_jaratok["stop_name"]=stop_name

df_megallo_jaratok[["stop_id","stop_name","route_id","arrival_time", "arrival_time_min", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,arrival_time_min,stop_headsign,stop_sequence
3,048506,Szent István Bazilika,4720,10:01:00,601,Zugló vasútállomás,9
1093,048506,Szent István Bazilika,0090,10:06:00,606,"Óbuda, Bogdáni út",17
401,048506,Szent István Bazilika,9500,24:09:00,1449,"Rákospalota, Székely Elek út",12
486,048506,Szent István Bazilika,9140,24:19:00,1459,"Káposztásmegyer, Mogyoródi-patak",30

## Most kiegészítjük az útvonal azonosítóval is (járatszám)

Ez még egy join

In [173]:
df_megallo_jaratok2 = pd.merge( df_megallo_jaratok, df_routes, left_on="route_id", right_on="route_id")
df_megallo_jaratok2[["stop_id","stop_name","route_id","arrival_time", "route_short_name", "stop_headsign","stop_sequence"]]

,stop_id,stop_name,route_id,arrival_time,route_short_name,stop_headsign,stop_sequence
0,048506,Szent István Bazilika,4720,10:01:00,72,Zugló vasútállomás,9
1,048506,Szent István Bazilika,0090,10:06:00,9,"Óbuda, Bogdáni út",17
2,048506,Szent István Bazilika,9500,24:09:00,950,"Rákospalota, Székely Elek út",12
3,048506,Szent István Bazilika,9140,24:19:00,914,"Káposztásmegyer, Mogyoródi-patak",30

In [174]:
stop_id = "F00933"
stop_id = "F01029"

parent_stop_id = df_stops[ df_stops["stop_id"] == stop_id]["parent_station"].iloc[0]
parent_stop_id

nan

Melyek azok az állomások amiknek van főmegállója?

# KÖZELI ÁTSZÁLLÁSI PONTOK

Ez úgy tűnik földrajzi koordináták alapján kell megkeresni.

In [175]:

# Create a list of Point objects
points = [Point(xy) for xy in zip(df_stops['stop_lon'], df_stops['stop_lat'])]

# Create a GeoSeries from the list of points with the correct CRS
gs = gpd.GeoSeries(points, crs='EPSG:4326')

gdf_stops = gpd.GeoDataFrame(df_stops, geometry=gs, crs="EPSG:4326")
gdf_stops.head(5)

,stop_id,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding,geometry
0,002133,"Örs vezér tere M+H, déli tárolótér",47.500366,19.135700,002133,NaN,NaN,NaN,NaN,POINT (19.1357 47.50037)
1,002138,Kőbánya alsó vasútállomás,47.483139,19.127891,002138,NaN,NaN,NaN,2.0,POINT (19.12789 47.48314)
2,003002,Puskás Ferenc Stadion M,47.500368,19.103406,003002,NaN,NaN,NaN,NaN,POINT (19.10341 47.50037)
3,004716,"ÉD metró járműtelep,porta",47.469651,19.129090,004716,NaN,NaN,NaN,2.0,POINT (19.12909 47.46965)
4,004948,Metró ÉD járműtelep (kapu),47.465239,19.142612,004948,NaN,NaN,NaN,NaN,POINT (19.14261 47.46524)

Az EPSG:4326 nem jó távolságmérésre, mert nem tudom miért.
De a 3035 az jó, Németországhoz kötött valami. Ezért átmegyek arra:

In [176]:
gdf_stops.to_crs("epsg:3035",inplace=True)
gdf_stops.head(5)

,stop_id,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding,geometry
0,002133,"Örs vezér tere M+H, déli tárolótér",47.500366,19.135700,002133,NaN,NaN,NaN,NaN,POINT (5007781.301 2752100.781)
1,002138,Kőbánya alsó vasútállomás,47.483139,19.127891,002138,NaN,NaN,NaN,2.0,POINT (5007426.257 2750125.866)
2,003002,Puskás Ferenc Stadion M,47.500368,19.103406,003002,NaN,NaN,NaN,NaN,POINT (5005367.638 2751801.574)
3,004716,"ÉD metró járműtelep,porta",47.469651,19.129090,004716,NaN,NaN,NaN,2.0,POINT (5007694.861 2748647.499)
4,004948,Metró ÉD járműtelep (kapu),47.465239,19.142612,004948,NaN,NaN,NaN,NaN,POINT (5008764.678 2748285.946)

Most a Nyugatihoz viszonyítva fogunk közeli megállókat keresni

In [177]:
stop_id = "F01029" # Nyugati
gdf_nyugati = gdf_stops [ gdf_stops["stop_id"] == stop_id ]
gdf_megallo = gdf_nyugati.to_crs(epsg=3035)
gdf_megallo

,stop_id,stop_name,stop_lat,stop_lon,stop_code,location_type,location_sub_type,parent_station,wheelchair_boarding,geometry
2579,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01029,NaN,NaN,NaN,1.0,POINT (5001786.02 2752416.904)

In [178]:
gdf_nearest_stops = gdf_megallo.sjoin_nearest(gdf_stops,distance_col="distance", how="right", exclusive = True, max_distance = 500)
gdf_nearest_stops.columns
#gdf_nearest_stops[["stop_id_left","stop_name_left","stop_lat_left","stop_lon_left","stop_id_right","stop_name_right","stop_lat_right","stop_lon_right","distance"]]

Index(['index_left', 'stop_id_left', 'stop_name_left', 'stop_lat_left',
       'stop_lon_left', 'stop_code_left', 'location_type_left',
       'location_sub_type_left', 'parent_station_left',
       'wheelchair_boarding_left', 'stop_id_right', 'stop_name_right',
       'stop_lat_right', 'stop_lon_right', 'stop_code_right',
       'location_type_right', 'location_sub_type_right',
       'parent_station_right', 'wheelchair_boarding_right', 'geometry',
       'distance'],
      dtype='object')

In [179]:
gdf_nearest_stops.nsmallest(40,'distance')[["stop_id_left","stop_name_left","stop_lat_left","stop_lon_left","stop_id_right","stop_name_right","stop_lat_right","stop_lon_right","distance"]]

,stop_id_left,stop_name_left,stop_lat_left,stop_lon_left,stop_id_right,stop_name_right,stop_lat_right,stop_lon_right,distance
2503,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00935,Nyugati pályaudvar M,47.509922,19.056658,39.253332
6099,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYI,Nyugati pályaudvar [I],47.509870,19.056404,56.669957
2502,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00934,Nyugati pályaudvar M,47.509896,19.056394,57.835671
6095,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYE,Nyugati pályaudvar [E],47.510447,19.056426,89.626772
6098,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYH,Nyugati pályaudvar [H],47.510233,19.056103,91.944253
2501,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00933,Nyugati pályaudvar M,47.510300,19.056167,92.071854
6097,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYG,Nyugati pályaudvar [G],47.510326,19.056196,92.107868
6090,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NY3,Nyugati pályaudvar (lift » M3),47.510040,19.055784,106.075445
129,F01029,Nyugati pályaudvar M,47.509806,19.057151,008137,Nyugati pályaudvar,47.510571,19.056072,117.418620
6096,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYF,Nyugati pályaudvar [F],47.510703,19.056257,120.137919
6088,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NY1,Nyugati pályaudvar,47.510545,19.055967,121.026471
1349,F01029,Nyugati pályaudvar M,47.509806,19.057151,102861,Nyugati pályaudvar M,47.510757,19.056308,123.147823
1395,F01029,Nyugati pályaudvar M,47.509806,19.057151,118346,Nyugati pályaudvar M (Podmaniczky utca),47.509276,19.058597,123.614908
2581,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01031,Nyugati pályaudvar M (Podmaniczky utca),47.509276,19.058597,123.614908
6188,F01029,Nyugati pályaudvar M,47.509806,19.057151,MERGED_F01031,Nyugati pályaudvar M (Podmaniczky utca),47.509276,19.058597,123.614908
2578,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01028,Nyugati pályaudvar M,47.510769,19.056301,124.561703
1639,F01029,Nyugati pályaudvar M,47.509806,19.057151,CSF00936,Nyugati pályaudvar,47.510768,19.056111,132.347975
6094,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYD,Nyugati pályaudvar [D],47.511026,19.057148,135.694557
2580,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01030,Nyugati pályaudvar M (Podmaniczky utca),47.509123,19.058664,136.686791
2577,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01027,Nyugati pályaudvar M,47.511012,19.056487,142.970302
2505,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00937,Nyugati pályaudvar,47.510828,19.055952,144.887681
2576,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01025,Nyugati pályaudvar M,47.510994,19.056288,147.022687
1127,F01029,Nyugati pályaudvar M,47.509806,19.057151,071659,Nyugati pályaudvar M,47.509906,19.055040,159.303033
6100,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYJ,Nyugati pályaudvar [J],47.510011,19.055055,159.378447
6103,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYM,Nyugati pályaudvar [M],47.510917,19.055716,163.833368
2575,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01024,Nyugati pályaudvar M,47.511228,19.056474,165.985563
6101,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYK,Nyugati pályaudvar [K],47.510513,19.055031,177.676246
6093,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYC,Nyugati pályaudvar [C],47.511509,19.056730,191.929523
2574,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01023,Nyugati pályaudvar M,47.511524,19.056686,194.132545
6102,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYL,Nyugati pályaudvar [L],47.510792,19.055004,194.999986
2504,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00936,Nyugati pályaudvar,47.511720,19.056873,213.831208
6089,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NY2,Nyugati pályaudvar,47.511807,19.056937,223.082319
6092,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYB,Nyugati pályaudvar [B],47.512118,19.057114,257.157912
6091,F01029,Nyugati pályaudvar M,47.509806,19.057151,LM3NYA,Nyugati pályaudvar [A],47.512240,19.056584,273.904365
2508,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00940,Báthory utca / Bajcsy-Zsilinszky út,47.507189,19.055730,310.513995
2506,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00938,Báthory utca / Bajcsy-Zsilinszky út,47.507063,19.054270,375.050159
2507,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00939,Báthory utca / Bajcsy-Zsilinszky út,47.506506,19.055716,383.024550
2615,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01068,Ferdinánd híd (Izabella utca),47.510112,19.062341,392.416066
2619,F01029,Nyugati pályaudvar M,47.509806,19.057151,F01072,Ferdinánd híd (Izabella utca),47.511037,19.062659,437.269358
2500,F01029,Nyugati pályaudvar M,47.509806,19.057151,F00932,Szent István körút,47.512046,19.052319,440.165891